language: node_js
node_js:
- '8'
dist: trusty
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: G27uqGc0OvCWcG/EXJC+sxH6BBZjbJlvJcmP6SjLjWrTNzKmM8O7DrtvmBQ1EOnS1WdZmsTPTMgfplnTFy1isi8QngPUAzMUwlNskzT6I5fWHZMZkv4JTNe3d7KFW2b5b0h2P3oO5xzVwnVe2V3aP9QzVW2Hn4u0kyCGofI3s14=
  app:
    master: shorty-prod
    develop: shorty-stage
