<?php
/**
 * - ShortyUrlTest.php
 *
 * @author  chris
 * @created 16/05/15 10:39
 */
namespace Shorty\Tests\Model;

use Kurl\Maths\Encode\Base62;
use Shorty\Model\ShortyUrl;

class ShortyUrlTest extends \PHPUnit_Framework_TestCase
{

    /**
     * A short URL fixture.
     *
     * @var ShortyUrl
     */
    private $fixture;
    /**
     * Ensure the links json serialise correctly.
     */
    public function testJsonSerialize()
    {
        $this->assertEquals(
            '{"id":"Ak","url":"http:\/\/example.com","clicks":0,"created":"2015-01-01T00:00:01+00:00"}',
            json_encode($this->fixture)
        );
    }

    /**
     * @expectedException \InvalidArgumentException
     * @expectedExceptionMessage Config is missing the following keys: id, url, clicks, created
     */
    public function testMissingKeys()
    {
        new ShortyUrl(array());
    }

    /**
     * @inheritDoc
     */
    protected function setUp()
    {
        $this->fixture = new ShortyUrl(
            ['id' => 666, 'url' => 'http://example.com', 'clicks' => 0, 'created' => '2015-01-01 00:00:01']
        );
        parent::setUp();
    }

    /**
     * @inheritDoc
     */
    protected function tearDown()
    {
        $this->fixture = null;
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
